version: '3'
services:  
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
    environment:
      NODE_ENV: dev

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/test
    environment:
      NODE_ENV: test

  vue-app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      NODE_ENV: prod